### PR TITLE
merge

### PR DESCRIPTION
**Pull request by mmhobi7**

### CODE REVIEW

**Comment by mmhobi7** [comment]
Can you believe this is only our 69th merge?

**Comment by Slydelix** [comment]
yeah xD
and the most fucked up one

**Comment by mmhobi7** [comment]
I'm like 80℅sure u fucked up 😂

**Comment by Slydelix** [comment]
blyat listen they forcing their fucked up boot shit but we already have one... both fucked up... now mixed... it's a recipe for a disaster... i reverted back to cm default boot thing

**Comment by mmhobi7** [comment]
No they changed the boot shit
Just revert to Thiers and then see how it looks, then change it again

**Comment by Slydelix** [comment]
i already reverted the merge and shit

**Pull request merged**
